import { IStudentDetails } from "./student-details.interface";

export const studentDetailsModel :IStudentDetails = {
    "SCHOOL_ID": 0,
    "ACADEMIC_ID": 0,
    "ADMN_NO": '',
    "ADMIN_DATE": null,
    "STUD_FIRST_NAME": null,
    "STUD_CLASS": null,
    "STUD_LAST_NAME": null,
    "STUD_FATH_NAME": null,
    "STUD_MTHR_NAME": null,
    "STUD_GNDR": null,
    "STUD_DOB": null,
    "STUD_CASTE": null,
    "STUD_SUB_CASTE": null,
    "STUD_CMTY": null,
    "STUD_RLIG": null,
    "STUD_NTLY": null,
    "STUD_MTHR_TNGE": null,
    "STUD_LNG_KNWN": null,
    "STUD_BLD_GRUP": null,
    "STUD_AHAR_NO": null,
    "STUD_EMIS_NO": null,
    "STUD_PREV_SCHL": null,
    "STUD_DISCOUNT": 0.0,
    "STUD_IS_ACTIVE": false,
    "CRET_TS": null,
    "LAST_UPDT_TS": null
}